/* Civic Signal: Admin control center; real dashboard metrics come from the Worker, while module cards remain safe placeholders until their APIs are enabled. */
import { useEffect, useState } from "react";
import { Activity, BarChart3, Bell, CalendarDays, ClipboardCheck, FileCheck2, Hammer, KeyRound, LogOut, Map, Search, Settings2, ShieldCheck, Users, ArrowLeftRight } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import { clearSession, getAdminDashboard } from "@/lib/api";

const modules = [
  ["Inspection", "จัดการการตรวจ", ClipboardCheck], ["Ranking", "การจัดอันดับ", BarChart3], ["Users", "จัดการผู้ใช้", Users], ["Locations", "จัดการสถานที่", Map], ["Approval", "ศูนย์อนุมัติ", FileCheck2], ["Maintenance", "ระบบแจ้งซ่อม", Hammer], ["Attendance", "ติดตามการเช็กชื่อ", ShieldCheck], ["Proxy", "การตรวจแทน", ArrowLeftRight], ["Alerts", "การแจ้งเตือน", Bell], ["Audit Log", "ประวัติการใช้งาน", Search], ["Reports", "การออกรายงาน", Activity], ["Calendar", "จัดการปฏิทิน", CalendarDays], ["Settings", "ตั้งค่าระบบ", Settings2],
] as const;

export default function Admin() {
  const [, navigate] = useLocation();
  const [session] = useState(() => { try { return JSON.parse(sessionStorage.getItem("sangkha_session") || localStorage.getItem("sangkha_session") || "{}"); } catch { return {}; } });
  const [stats, setStats] = useState({ completed: 0, pending: 0, totalLocations: 0, average: 0, users: 0 });
  const [loading, setLoading] = useState(true);

  useEffect(() => { getAdminDashboard(session.sessionId).then(setStats).catch((error) => toast.error(error instanceof Error ? error.message : "โหลดข้อมูล Admin ไม่สำเร็จ")).finally(() => setLoading(false)); }, [session.sessionId]);
  function logout() { clearSession(); navigate("/login"); }

  const metrics = [["คะแนนรวมเฉลี่ย", `${stats.average.toFixed(1)}%`, "text-[#07835f]", BarChart3], ["ตรวจแล้ววันนี้", `${stats.completed}/${stats.totalLocations}`, "text-[#ab0013]", ClipboardCheck], ["รอดำเนินการ", String(stats.pending), "text-[#be6a12]", Activity], ["ผู้ใช้งานทั้งหมด", String(stats.users), "text-[#705d00]", Users]] as const;
  return <div className="min-h-screen bg-[#eef1f3] text-[#142436]">
    <aside className="fixed inset-y-0 left-0 hidden w-72 flex-col justify-between bg-[#142436] p-7 text-white lg:flex"><div><div className="flex items-center gap-3"><img src="/manus-storage/sangkha-mark_05f1f42c.png" alt="ตราสัญลักษณ์" className="h-11 w-11 rounded-xl bg-white p-1" /><div><p className="font-display font-semibold">Sangkha School</p><p className="text-xs text-white/55">Admin Operations</p></div></div><div className="mt-14"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ffb4ac]">Admin control</p><h1 className="mt-3 font-display text-4xl font-semibold leading-tight">คุมระบบ<br /><span className="text-[#ffb4ac]">ให้เห็นภาพรวม</span></h1><p className="mt-5 text-sm leading-6 text-white/62">จัดการข้อมูลกลาง การตรวจ และสถานะการปฏิบัติงานของโรงเรียน</p></div></div><div className="border-t border-white/10 pt-5 text-xs text-white/50">ข้อมูลแสดงตามสิทธิ์ Admin</div></aside>
    <main className="min-h-screen lg:ml-72"><header className="sticky top-0 z-20 flex items-center justify-between border-b border-[#dce1e4] bg-white/90 px-5 py-4 backdrop-blur sm:px-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#ab0013]">Admin / วันนี้</p><h2 className="font-display text-2xl font-semibold">Admin Dashboard</h2></div><button onClick={logout} className="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-[#ab0013] hover:bg-[#f9e8e7]"><LogOut className="h-4 w-4" /> ออกจากระบบ</button></header>
      <div className="mx-auto max-w-7xl px-5 py-7 sm:px-8"><section className="relative mb-7 overflow-hidden rounded-3xl bg-[#ab0013] p-6 text-white shadow-xl sm:p-8"><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm text-white/70">ผู้ดูแลระบบ</p><h3 className="mt-2 font-display text-3xl font-semibold">{session.user?.Full_Name || "Admin"}</h3><p className="mt-2 text-white/75">รหัส {session.user?.Student_ID || "—"} · ควบคุมทุกประเภทงาน</p></div><div className="rounded-2xl bg-white/12 px-4 py-3 text-right backdrop-blur"><p className="text-xs text-white/65">สถานะระบบ</p><p className="mt-1 font-display text-xl font-semibold">{loading ? "กำลังโหลด" : "เชื่อมต่อแล้ว"}</p></div></div></section>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, color, Icon]) => <div key={label} className="rounded-2xl border border-[#dce1e4] bg-white p-4 shadow-sm"><div className={`flex h-10 w-10 items-center justify-center rounded-xl bg-[#f4f6f8] ${color}`}><Icon className="h-5 w-5" /></div><p className="mt-5 font-display text-3xl font-semibold">{loading ? "—" : value}</p><p className="mt-1 text-sm text-[#71808c]">{label}</p></div>)}</div>
        <section className="mt-7 rounded-2xl border border-[#dce1e4] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#ab0013]">Admin modules</p><h3 className="mt-1 font-display text-xl font-semibold">เมนูจัดการระบบ</h3></div><KeyRound className="h-5 w-5 text-[#ab0013]" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{modules.map(([english, thai, Icon]) => <button key={english} onClick={() => toast.info(`${english}: หน้านี้จะเชื่อม API ในขั้นตอนถัดไป`)} className="group flex items-center gap-3 rounded-xl border border-[#e5e8ea] bg-white p-3 text-left transition hover:-translate-y-0.5 hover:border-[#ab0013] hover:shadow-sm active:scale-[.98]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#f9e8e7] text-[#ab0013]"><Icon className="h-5 w-5" /></span><span><b className="block font-semibold">{thai}</b><small className="text-xs text-[#71808c]">{english}</small></span></button>)}</div></section></div></main>
  </div>;
}
